### PR TITLE
Add new functionality for ComressionAlgorithmController

### PR DESCRIPTION
**Pull request by aleksei-kashapov**
Give more functionality for pytorch model export to ONNX:

* add **strip_model()** for compression controllers with implementation for _FilterPruningController_
* change **export_model()** for _FilterPruningController_ and _CompositeCompressionAlgorithmController_

### CODE REVIEW

**Review by AlexKoff88 — APPROVED** [review]

**Comment by vshampor** [comment]
@alexsu52 I think that `strip_model` is too specific a name for an entire possible range of changes that may have to be made for a model to be successfully prepared for export. Can we perhaps both switch to one of the following names for the function: 

`prepare_model_for_export`, `prepare_for_export`, `finalize_for_export`?

@aleksei-kashapov please rebase your PR branch so that only one commit is added here.

**Comment by aleksei-kashapov** [comment]
@vshampor is `finish_algorithm()` a good name for pre-export actions?
if not please indicate the most likable version for you and I will use it

**Comment by AlexKoff88** [comment]
> @vshampor is `finish_algorithm()` a good name for pre-export actions?
> if not please indicate the most likable version for you and I will use it

I think it is not the best one because it does not reflect what should happen inside. Let's end up with something like `prepare_for_export()`

**Comment by aleksei-kashapov** [comment]
done!

**Review by AlexKoff88 — APPROVED** [review]

**Comment by aleksei-kashapov** [comment]
@alexsu52, @vanyalzr could you look at this PR, please?

**Pull request merged**
